version: "3.1"
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_3.1.5_container_mand
    ports:
      - 80:80
    volumes:
      - /Users/henrynavntoft/Desktop/web_mand_1:/app
    networks:
      - bottle_arangodb_network

  arangodb:
    image: arangodb:3.11.3
    container_name: x_arango_3.11.3_container_mand
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - /Users/henrynavntoft/Desktop/web_mand_1/arangodb:/var/lib/arangodb3
    networks:
      - bottle_arangodb_network

networks:
  bottle_arangodb_network:
